#!/usr/bin/env python3
"""
Fault-injection master for Micro-UXI.

Place this file and fault_config.json in the fault-injection/ folder.
Output dataset: ground_truth.jsonl only.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def append_jsonl(path: Path, record: dict[str, Any]) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")
        f.flush()


def normalize_event(value: str) -> str:
    value = value.strip().upper()
    if value in {"1", "2", "3", "4", "5", "6"}:
        return f"S{value}"
    return value


def write_fi_config(cfg: dict[str, Any], base_dir: Path) -> None:
    env_file = base_dir / cfg.get("fi_config_file", "fi_config.env")
    lines = ["# Generated by fault_master.py\n"]
    for key, value in cfg.get("fi_env", {}).items():
        lines.append(f"{key}={value}\n")
    with env_file.open("w", encoding="utf-8") as f:
        f.writelines(lines)


def parse_set(values: list[str]) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in values:
        if "=" not in item:
            raise SystemExit(f"Invalid --set '{item}'. Use KEY=VALUE.")
        key, value = item.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def coerce_like(old: Any, new: str) -> Any:
    if isinstance(old, bool):
        return new.lower() in {"1", "true", "yes", "y"}
    if isinstance(old, int):
        return int(new)
    if isinstance(old, float):
        return float(new)
    return new


def apply_overrides(params: dict[str, Any], overrides: dict[str, str]) -> dict[str, Any]:
    merged = dict(params)
    for key, value in overrides.items():
        if key in merged:
            merged[key] = coerce_like(merged[key], value)
        else:
            merged[key] = value
    return merged


def render_args(template: list[str], params: dict[str, Any]) -> list[str]:
    rendered = []
    for item in template:
        rendered.append(item.format(**params))
    return rendered


def run_cmd(cmd: list[str], cwd: Path) -> None:
    print("$ " + " ".join(cmd), flush=True)
    completed = subprocess.run(cmd, cwd=str(cwd))
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run one fault injection and append one ground-truth row.")
    parser.add_argument("--event", required=True, help="S1, S2, S3, S4, S5, or S6")
    parser.add_argument("--run-id", required=True, help="Example: S3_RUN_01")
    parser.add_argument("--config", default="fault_config.json")
    parser.add_argument("--output", default=None, help="Override output JSONL file")
    parser.add_argument("--duration", type=int, default=None, help="Override duration for start_stop mode")
    parser.add_argument("--set", action="append", default=[], metavar="KEY=VALUE", help="Override fault_parameter, e.g. --set loss_pct=40")
    parser.add_argument("--repeat", type=int, default=None, help="Override jumlah iterasi injeksi fault")
    parser.add_argument("--grace-period", type=int, default=None, help="Override grace period (detik)")
    args = parser.parse_args()

    if hasattr(os, "geteuid") and os.geteuid() != 0:
        raise SystemExit("Run with sudo: sudo python3 fault_master.py --event S3 --run-id S3_RUN_01")

    base_dir = Path.cwd().resolve()
    config_path = Path(args.config)
    if not config_path.is_absolute():
        config_path = base_dir / config_path

    cfg = load_json(config_path)
    event_code = normalize_event(args.event)
    events = cfg["events"]

    if event_code not in events:
        valid = ", ".join(sorted(events.keys()))
        raise SystemExit(f"Unknown event '{event_code}'. Valid: {valid}")

    if cfg.get("write_fi_config", True):
        write_fi_config(cfg, base_dir)

    event_cfg = events[event_code]
    event_type = event_cfg["event_type"]
    target = event_cfg["target"]
    script_path = base_dir / event_cfg["script"]
    mode = event_cfg["mode"]
    params = apply_overrides(event_cfg.get("fault_parameter", {}), parse_set(args.set))
    duration = args.duration if args.duration is not None else event_cfg.get("duration_sec")

    repeat = args.repeat if args.repeat is not None else event_cfg.get("repeat", cfg.get("repeat", 30))
    grace_period = args.grace_period if args.grace_period is not None else event_cfg.get("grace_period_sec", cfg.get("grace_period_sec", 60))

    if not script_path.exists():
        raise SystemExit(f"Fault script not found: {script_path}")

    output_file = Path(args.output or cfg.get("output_file", "ground_truth.jsonl"))
    if not output_file.is_absolute():
        output_file = base_dir / output_file

    print(f"[FAULT_MASTER] run_id_base={args.run_id} event={event_code} type={event_type}")
    print(f"[FAULT_MASTER] script={script_path.name} | repeat={repeat}x | grace={grace_period}s")
    print(f"[FAULT_MASTER] dataset={output_file}\n")

    rollback_script = base_dir / "rollback_all_faults.sh"

    for i in range(1, repeat + 1):
        current_run_id = f"{args.run_id}_{i:02d}" if repeat > 1 else args.run_id
        print(f"=== [FAULT_MASTER] Iteration {i}/{repeat} | run_id={current_run_id} ===")
        
        start_time = now_iso()
        try:
            if mode == "start_stop":
                start_args = render_args(event_cfg["start_args"], params)
                stop_args = render_args(event_cfg["stop_args"], params)
                if duration is None:
                    raise SystemExit("duration_sec is required for start_stop mode")

                run_cmd([str(script_path), *start_args], base_dir)
                try:
                    time.sleep(int(duration))
                finally:
                    run_cmd([str(script_path), *stop_args], base_dir)

            elif mode == "single_command":
                cmd_args = render_args(event_cfg["args"], params)
                run_cmd([str(script_path), *cmd_args], base_dir)

            else:
                raise SystemExit(f"Unsupported mode: {mode}")

        finally:
            end_time = now_iso()

        record = {
            "run_id": current_run_id,
            "event_type": event_type,
            "start_time": start_time,
            "end_time": end_time,
            "target": target,
            "fault_parameter": params
        }
        append_jsonl(output_file, record)
        print(f"[FAULT_MASTER] ground truth written: {output_file}")

        if i < repeat:
            print(f"[FAULT_MASTER] Mengembalikan jaringan (rollback) dan masuk grace period {grace_period} detik...\n")
            if rollback_script.exists():
                subprocess.run(["bash", str(rollback_script)], cwd=str(base_dir))
            time.sleep(grace_period)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
